@baseURL = http://localhost:3123

### GET 

GET {{baseURL}}/products/

### POST 

POST {{baseURL}}/products/
Content-Type: application/json

{
	"product": "TestBeer3",
	"warehouses": [
		{
			"name":"Göteborg",
			"amount": 50
		},
		{
			"name": "Helsingfors",
			"amount": 40
		},
		{
			"name": "Vasa",
			"amount": 24
		}
	]
}

