@baseURL = http://localhost:3123

@token = Bearer {{$dotenv API_TEST}}

### GET 

GET {{baseURL}}/products/
Authorization: {{token}}

### GET 

GET {{baseURL}}/products/inventorytest01
Authorization: {{token}}

### POST 

POST {{baseURL}}/products/
Content-Type: application/json
Authorization: {{token}}

{
	"product": "inventorytest01"
}

### POST 

POST {{baseURL}}/products/
Content-Type: application/json
Authorization: {{token}}

{
	"product": "inventorytest01",
	"warehouses": [
		{
			"name":"Göteborg",
			"amount": 20
		},
		{
			"name": "Helsingfors",
			"amount": 31
		}
	]
}

### PATCH

PATCH {{baseURL}}/products/customid56758r9347462358
Content-Type: application/json
Authorization: {{token}}

{
	"product": "customid56758r9347462358",
	"warehouses": [
		{
			"name":"Göteborg",
			"amount": 20
		},
		{
			"name": "Helsingfors",
			"amount": 31
		},
		{
			"name": "Vasa",
			"amount": 0
		}
	]
}

### PATCH adjust

PATCH {{baseURL}}/products/adjust/inventorytest01
Content-Type: application/json
Authorization: {{token}}

{
	"warehouse": "Göteborg",
	"amount": -8
}

### GET repost so I dont have to scroll

GET {{baseURL}}/products/inventorytest01
Authorization: {{token}}

### DELETE

DELETE {{baseURL}}/products/inventorytest01
Content-Type: application/json
Authorization: {{token}}