@baseURL = http://localhost:3123

### GET 

GET {{baseURL}}/warehouses/

### POST 

POST {{baseURL}}/warehouses/
Content-Type: application/json

{
    "name": "Helsinki",
    "address": "Romgatan 5"
}

### POST 

POST {{baseURL}}/warehouses/
Content-Type: application/json

{
    "name": "Vasa",
    "address": "Vasa gatan 5"
}

