@baseURL = http://localhost:3123

@token = Bearer {{$dotenv API_TEST}}

### GET 

GET {{baseURL}}/warehouses/
Authorization: {{token}}

### POST 

POST {{baseURL}}/warehouses/
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Helsinki",
    "address": "Romgatan 5"
}

### POST 

POST {{baseURL}}/warehouses/
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Greta",
    "address": "Test"
}

### PATCH 

PATCH {{baseURL}}/warehouses/636bbd97a0fd5afc062a5999
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Gråta",
    "address": "Test2"
}

### DELETE

DELETE {{baseURL}}/warehouses/636bbd97a0fd5afc062a5999
Content-Type: application/json
Authorization: {{token}}

{
    "name": "Greta",
    "address": "Test"
}